# Generated by Django 3.0.6 on 2020-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_detail',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
