# Generated by Django 3.0.6 on 2020-10-14 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201014_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_detail',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
