# Generated by Django 3.0.6 on 2020-10-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201015_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_detail',
            old_name='person',
            new_name='email',
        ),
    ]
