# Generated by Django 3.0.6 on 2020-10-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201015_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_detail',
            old_name='email',
            new_name='person_id',
        ),
    ]
