# Generated by Django 3.0.6 on 2020-10-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201015_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_detail',
            old_name='person_id',
            new_name='Person',
        ),
    ]
