# Generated by Django 3.0.6 on 2020-10-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201015_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_detail',
            old_name='Person',
            new_name='person_id',
        ),
    ]
